services:
  mongo:
    build:
      context: ./database
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: nikita
      MONGO_INITDB_ROOT_PASSWORD: pasword
      MONGO_INITDB_DATABASE: mydatabase
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: always
